### ISSUE TITLE
Backups not created - oVirt 4.2.8

### ISSUE THREAD

**Issue by skunkr** [bacchus-ng/bacchus#47]
Hi Everyone,
Backup jobs are not created ( neither on-demand, nor scheduled ). Worker log shows this error:

Traceback (most recent call last):
  File "/usr/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 122, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
    self._conninfo.transport.implements.async and
  File "/usr/lib/python2.7/site-packages/kombu/transport/base.py", line 127, in __getattr__
    raise AttributeError(key)
AttributeError: async

Using oVirt 4.2.8.
Any suggestions ?

Thank you very much !

**Comment by matonb** [comment]
Have you tried updating celery?

 `pip install --upgrade celery`

**Comment by skunkr** [comment]
Thank you Brett ! 
I have updated celery as per you suggestion. 
Removed oVirt engine instance,  added it back ( for sake of a clean database )
On demand backups are still not created, task list is empty but worker.log is throwing now a different error:

[2019-02-10 14:17:53,470: ERROR/ForkPoolWorker-15] Task scheduler.tasks.run_schedule[dc07e298-6140-41b5-9cb6-d3d963ad875b] raised unexpected: DoesNotExist('Schedule matching query does not exist.',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/bacchus/scheduler/tasks.py", line 11, in run_schedule
    sched = Schedule.objects.get(id=sched_id)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
Exception: Schedule matching query does not exist.

Any ideea what should I do to fix this ?

**Comment by matonb** [comment]
Smells like a database issue, most likely a scheduled task from a previous attempt that doesn't exist anymore.

You could try removing any scheduled backups that are listed in the UI

**Comment by skunkr** [comment]
Indeed, there were some schedules configured but I have deleted them before upgrading celery.
I will try a fresh install, then first thing to update celery before adding any managers.

**Comment by matonb** [comment]
Worth a try, if that doesn't help maybe blow away the MySQL database before installing again.

I've not got to grips with what django gets upto in the its database under the covers yet.

**Comment by skunkr** [comment]
Yes,  this way it worked ( clean install -> upgrade celery -> reboot -> add manager ) !
I have successfully managed to create backups.
Thank you very much Brett !

**Comment by skunkr** [comment]
Hi again,
Not sure if there is something wrong that I've did,  but it seems that only on-demand backup jobs are working.
I have defined one schedule as follows : 5 * * * *    ( in my understanding to have a backup at 5 minutes past every hour ),  and no jobs are triggered.
In worker.log there are a lot of INFO,  but still no backup activity.
[2019-02-10 16:13:02,103: INFO/ForkPoolWorker-2] Task scheduler.tasks.run_schedule[41a6e5fe-976a-467b-b378-ecbd6be336cb] succeeded in 0.0167102539999s: True
[2019-02-10 16:13:02,108: INFO/ForkPoolWorker-5] Task scheduler.tasks.run_schedule[34ce759c-3087-4d45-8805-3ffb3f72c400] succeeded in 0.0157757460001s: True
[2019-02-10 16:13:02,111: INFO/MainProcess] Received task: scheduler.tasks.run_schedule[55c21e23-c88e-40cd-8123-2c5d29c6b7d8]
[2019-02-10 16:13:02,118: INFO/MainProcess] Received task: scheduler.tasks.run_schedule[86bf229f-6a42-4f6f-94b9-a4f837085f7d]
[2019-02-10 16:13:02,121: INFO/ForkPoolWorker-16] Task scheduler.tasks.run_schedule[1778ce1b-c191-4339-8acf-3af3e4db43bf] succeeded in 0.0186980949998s: True
[2019-02-10 16:13:02,126: INFO/ForkPoolWorker-14] Task scheduler.tasks.run_schedule[55c21e23-c88e-40cd-8123-2c5d29c6b7d8] succeeded in 0.0120529690003s: True
[2019-02-10 16:13:02,127: INFO/MainProcess] Received task: scheduler.tasks.run_schedule[05dca456-6ff5-49ab-b98c-d6e25bacddea]
[2019-02-10 16:13:02,135: INFO/MainProcess] Received task: scheduler.tasks.run_schedule[a6e4dec4-26e1-4563-8909-530992f8c565]
[2019-02-10 16:13:02,139: INFO/ForkPoolWorker-8] Task scheduler.tasks.run_schedule[86bf229f-6a42-4f6f-94b9-a4f837085f7d] succeeded in 0.0170977859998s: True
[2019-02-10 16:13:02,146: INFO/MainProcess] Received task: scheduler.tasks.run_schedule[609de27e-7113-4cbf-9c9f-c05793a9b829]
Any thoughts ?
Thanks !

**Comment by matonb** [comment]
Looks very similar to my logs, except no vms seem to have been selected for backup.

The first line is the scheduled task starting, the following two are the vm's that the task is to backup
The fourth line is the end of the task (starting the jobs, not backups completed).
```
[2019-01-22 20:00:00,008: INFO/MainProcess] Received task: scheduler.tasks.run_schedule[959ae96c-1d26-49ae-97b2-58f9931edca7]
[2019-01-22 20:00:00,050: INFO/MainProcess] Received task: manager.tasks.backup_vm[xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx]
[2019-01-22 20:00:00,058: INFO/MainProcess] Received task: manager.tasks.backup_vm[xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx]
[2019-01-22 20:00:00,068: INFO/ForkPoolWorker-10] Task scheduler.tasks.run_schedule[959ae96c-1d26-49ae-97b2-58f9931edca7] succeeded in 0.0558142869268s: True
```
Have you selected VM's to be backed up ?

**Comment by skunkr** [comment]
I have started a new fresh installation, trying to get that up and working. Thank you very much for support !
